name: Build and Release APK

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v2.8.0

permissions:
  contents: write  # Required for creating releases
  
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'
    
    - name: Decode Google Services JSON
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_CONTENT }}
      run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Rename APK with version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/spdrivercalendar-$VERSION.apk
    
    - name: Create Release and Upload APK
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## What's New in ${{ github.ref_name }}
          
          🔄 **Auto-Update System**
          - Automatic update checking and installation
          - Smart update frequency control  
          - Detailed release notes and installation guidance
          
          📱 **Download & Install**
          1. Download the APK below
          2. Enable "Install from Unknown Sources" in Android settings
          3. Install the APK
          4. Future updates will be automatic!
          
          ---
          *This release was automatically built and deployed via GitHub Actions*
        files: build/app/outputs/flutter-apk/spdrivercalendar-${{ github.ref_name }}.apk
        draft: false
        prerelease: false 